name: savannah

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: savannah
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - postgres
    env_file:
      - .env.example
    networks:
      - savannah

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - savannah

networks:
  savannah:
    driver: bridge
